[package]
name = "elbus"
version = "0.1.2"
edition = "2021"
authors = ["Sergei S. <div@altertech.com>"]
license = "Apache-2.0"
repository = "https://github.com/alttch/elbus"
description = "Local and network IPC bus"
readme = "README.md"
keywords = ["bus", "ipc", "pubsub"]
autoexamples = false

[dependencies]
tokio = { version = "1.15.0", features = ["full"] }
async-channel = "1.6.1"
log = { version = "0.4.14", optional = true }
syslog = { version = "5.0.0", optional = true }
chrono = { version = "0.4.19", optional = true }
colored = { version = "2", optional = true }
clap = { version = "=3.0.0-beta.2", optional = true }
clap_derive = { version = "=3.0.0-beta.2", optional = true }
submap = { version = "0.1.2", optional = true }
lazy_static = { version = "1.4.0", optional = true }
jemallocator = { version = "0.3.0", optional = true }
fork = { version = "0.1.18", optional = true }
rmp-serde = { version = "0.15.5", optional = true }
serde = { version = "1.0.127", features = ["derive"], optional = true }
async-trait = { version = "0.1.51", optional = true }
unix-named-pipe = { version = "0.2.0", optional = true }
serde_json = { version = "1.0.74", optional = true }
#bma-benchmark = "0.0.18"

[features]
server = ["log", "syslog", "chrono", "colored", "clap", "clap_derive",
          "lazy_static", "jemallocator", "fork", "broker"]
broker = ["log", "submap", "async-trait", "unix-named-pipe"]
broker-api = ["serde", "broker", "rpc"]
ipc = ["log", "async-trait"]
rpc = ["log", "rmp-serde", "async-trait", "serde_json"]
serialization = ["serde"]

[package.metadata.docs.rs]
features = ["broker-api", "ipc", "rpc"]

[package.metadata.playground]
features = ["broker-api", "ipc", "rpc"]

[lib]
name = "elbus"
path = "src/lib.rs"

[[bin]]
name = "elbusd"
path = "src/server.rs"
required-features = ["server"]

[[example]]
name = "inter_thread"
required-features = ["broker"]

[[example]]
name = "broker_custom_rpc"
required-features = ["broker", "rpc", "serialization"]

[[example]]
name = "client_rpc_handler"
required-features = ["ipc", "rpc", "serialization"]
